spring:
  # Druid数据源配置
  datasource:
    druid:
      # 公共配置
      initial-size: 5 # 初始连接数
      max-active: 5   # 最大连接池数量

  # Druid 数据源 1 配置
  datasource-one:
    url: jdbc:mysql://localhost:3306/database_one
    username: user_one
    password: pass_one
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 10 # 覆盖最大连接池数量
      max-wait: 10000 # 最长等待时间

  # Druid 数据源 2 配置
  datasource-two:
    url: jdbc:mysql://localhost:3306/database_two
    username: user_two
    password: pass_two
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20 # 覆盖最大连接池数量
      max-wait: 20000 # 最长等待时间